Fix compilation error:
TopQuarkAnalysis/TopPairBSM/src/BoostedTopProducer.cc:280:13: error:
variable 'nuzHasComplex' set but not used [-Werror=unused-but-set-variable]