Force plugins to link against pydata.o on slc5_amd64_gcc451.
This is required by the fact that otherwise it picks up an
undefined reference to the pydata common block at runtime.