Do not typedef `gzFile' as void *. EcalTrigPrimESProducer.h include zlib.h, which has `gzFile'.
SimCalorimetry/EcalTrigPrimProducers/plugins/EcalTrigPrimESProducer.cc:35:39:
error: invalid conversion from 'GzInputStream::gzFile {aka void*}' to
'gzFile' [-fpermissive]
     char * res = gzgets(gzf,buffer,256) ;